modLoader="javafml"
loaderVersion="[43,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="elementalcraft"
version="${file.jarVersion}"
displayName="ElementalCraft"
description='''ElementalCraft is a magic mod based around the 4 elements: fire, water, earth and air.'''

[[dependencies.elementalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="dpanvil"
    mandatory=true
    versionRange="[1.19.2-4.4.0,1.19.2-4.5.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="jei"
    mandatory=false
    versionRange="[11.6.0.1013,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.19-75,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="mekanism"
    mandatory=false
    versionRange="[1.19.1-10.3.1.468,)"
    ordering="AFTER"
    side="BOTH"
