modLoader="javafml"
loaderVersion="[36,)" 
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="elementalcraft"
version="${file.jarVersion}"
displayName="ElementalCraft"
description='''ElementalCraft is a magic mod based around the 4 elements: fire, water, earth and air.'''

[[dependencies.elementalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="dpanvil"
    mandatory=true
    versionRange="[1.16.4-1.1.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.16.4-7.6.1.71,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.16.2-47,)"
    ordering="AFTER"
    side="BOTH"
    